  feature/about-page[m
  feature/active-navbar[m
  feature/back-to-top-button[m
  feature/card-hover-animation[m
  feature/contact-form-validation-ui[m
  feature/contact-page[m
  feature/contact-success-message[m
  feature/cta-section[m
* [32mfeature/dark-mode-toggle[m
  feature/footer-component[m
  feature/hero-gradient[m
  feature/navbar-component[m
  feature/project-card-component[m
  feature/projects-page[m
  feature/responsive-navbar[m
  feature/section-title-component[m
  feature/section-title-component-v2[m
  feature/service-icons[m
  feature/testimonials-section[m
  master[m
